services:

  # Orion Context Broker LD
  orion:
    image: fiware/orion-ld:1.5.1
    depends_on:
      - mongo-db
    restart: always
    ports:
      - "1026:1026" # http://localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG -forwarding # -db orion -experimental
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  # Mongo DB for Orion
  mongo-db:
    image: mongo:4.4
    container_name: db-mongo
    restart: always
    command: --nojournal
    volumes:
      - mongo-db:/data/db
    # - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: mongo --eval "db.adminCommand('ping')" --quiet

volumes:
  mongo-db: ~
